/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class DniNieGenerator extends javax.swing.JFrame {
    private Dni d;
    private Nie n;
    private Cif c;
    

    /**
     * Creates new form DniNieGenerator
     */
    public DniNieGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDni = new javax.swing.JButton();
        bNie = new javax.swing.JButton();
        tResultafdo = new javax.swing.JTextField();
        lTitulo = new javax.swing.JLabel();
        bCif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bDni.setText("Generar DNI");
        bDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDniActionPerformed(evt);
            }
        });

        bNie.setText("Generar NIE");
        bNie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNieActionPerformed(evt);
            }
        });

        tResultafdo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tResultafdo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lTitulo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("GENERADOR DNI-NIE");

        bCif.setText("Generar Cif");
        bCif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bNie)
                        .addGap(18, 18, 18)
                        .addComponent(bCif))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(tResultafdo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(lTitulo)
                .addGap(45, 45, 45)
                .addComponent(tResultafdo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDni)
                    .addComponent(bNie)
                    .addComponent(bCif))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Crea un nuevo Dni y llama al metodo generar Dni
    private void bDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDniActionPerformed
            d = new Dni();
           tResultafdo.setText(d.generarDni().toString()); 
    }//GEN-LAST:event_bDniActionPerformed
//Crea un nuevo Nie y llama al metodo generar Nie
    private void bNieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNieActionPerformed
        n = new Nie();
       tResultafdo.setText(n.generarNie());
        
        
    }//GEN-LAST:event_bNieActionPerformed

    private void bCifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCifActionPerformed
        c = new Cif();
        try{
            tResultafdo.setText(c.generarCif());
        }catch(Exception e){
             String mensaje = "No se ha podido generar el Cif";
        String titulo = "Error";
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_bCifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DniNieGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DniNieGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DniNieGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DniNieGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DniNieGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCif;
    private javax.swing.JButton bDni;
    private javax.swing.JButton bNie;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tResultafdo;
    // End of variables declaration//GEN-END:variables
}
